site_name: Contemporary Thoughts
nav:
  - Index: 'index.md'
  - Introduction: 'intro.md'
theme:
  name: material

  features: 
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabls.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  
  icon:
    logo: logo
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/giacomo-miceli-phd/
    - icon: fontawesome/brands/github
      link: https://github.com/giafrale
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gia_miceli

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2023 Giacomo Miceli
